server:
  port: 12345

spring:
  datasource:
    url: jdbc:mysql://39.96.84.144:3306/market_supervision?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
#  mvc:
#    static-path-pattern: /**

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: market.constant

#showSql
logging:
  level.market.init.dao : debug


