server:
  port: 12345
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market_supervision?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
    encoding:
      charset: utf-8
      force: true
      enabled: true
#  mvc:
#    static-path-pattern: /**

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: market.constant

#showSql
logging:
  level.market.init.dao : debug



